// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"github.com/AlfaSakan/twitter-clone-api/src/repositories"
)

// Injectors from injector.go:

func InitializedUserService(ur repositories.IUserRepository) *UserService {
	userService := NewUserService(ur)
	return userService
}
