// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repositories

import (
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitializedUserRepository(db *gorm.DB) *UserRepository {
	userRepository := NewUserRepository(db)
	return userRepository
}

func InitializedTweetRepository(db *gorm.DB) *TweetRepository {
	tweetRepository := NewTweetRepository(db)
	return tweetRepository
}
