// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"github.com/AlfaSakan/twitter-clone-api/src/services"
)

// Injectors from injector.go:

func InitializedUserHandler(us services.IUserService) *UserHandler {
	userHandler := NewUserHandler(us)
	return userHandler
}
